### ISSUE TITLE
Doesn't seem to do anything?

### ISSUE THREAD

**Issue by steveharman** [nigelm/OctoPrint-MoteLightingControl#1]
HI Nigel.  I have a Pi 4 with a Mote PHAT fitted - all the LEDs seem to work fine from the various test scripts that Pimoroni have in their Repo - but I can't get your OctoPrint plugin to do anything.

For example at a simplest level; pressing the light bulb icon at the top of the screen which I presume is manual mode - nothing happens on the LED strips.

Is there anything I can do to try & debug?

Thanks

**Comment by nigelm** [comment]
Ah - I obviously have not made this obvious in the README, but as I had no way of testing with a PHAT (my Motes are USB connected), and the API looked sufficiently different that I didn't have any confidence it would work, I took out the code I originally lifted from https://github.com/topshed/OctoPrintMote to support it.

If you are able to put a little work into testing the PHAT version then I'd be able to either try and add support or assist you in adding support depending how confident you were in givung it a go.

There was some code removed in https://github.com/nigelm/OctoPrint-MoteLightingControl/commit/668c438c9194ce1ad3e3bb1a810af9a29b23c7af to take out PHAT support - but just reversing that commit will not be sufficient as there is son subsequent refactoring.

If you are happy to give it a go I would be delighted to take a pull request or even the outline of a pull requets to sort this...


  Nigel.

**Comment by steveharman** [comment]
Hi Nigel.  

More than happy to help with any testing & feedback.  I'm not a developer as such, but professionally have have spent more years than I care to mention in the industry so am happy to dive into code editing, reading logs and general QA - if you point me in the right direction!

Steve

**Comment by nigelm** [comment]
Try installing from here:-

   https://github.com/nigelm/OctoPrint-MoteLightingControl/archive/motephat.zip

Hopefully it should just work, but obviously not tested against your hardware :-)

**Comment by steveharman** [comment]
Hi Nigel,  

I've installed the .zip of the `motephat` branch but sadly I'm no further forward - neither of my light sticks want to respond to manual control from the "bulb" icon in Octoprint's web UI.  I Haven't attempted a print yet but will let you know if any of the printing states generate a response from the LEDs.

_Update: No LEDs light when a print job starts or runs._

**ENVIRONMENT**

- Raspberry Pi 4
- Pimoroni Mote Phat
- 2 x Pimoroni RGB light sticks
- Pimoni Python library installed (`https://github.com/pimoroni/mote-phat`)

I've run the `test.py `script (and others) that come with the library and my sticks respond as expected, cycling through their RGB or whatever.

An unrelated observation, which is common to the `main` branch as well as `motephat` - the little bulb icon which I assume invokes the Manual Lighting Colour (white) seems to remove Octoprint's "System" menu item, so there's no way for the user to restart or reboot Octoprint / the Pi after installing Mote Lighting Control:

<img width="835" alt="OCTOMOTE" src="https://user-images.githubusercontent.com/12557929/127304639-4c7b450f-9df3-4f3a-876c-1aedd564ac32.png">

Steve

**Comment by nigelm** [comment]
Please could you get a shell session on your pi as the user that OctoPrint runs as (for me thats the pi user, but can't remember if thats standard or configurable).

In that account there are log files in `~/.octoprint/logs/`

Have a look at the `octoprint.log` file, and look for log entries with `mote` or `Mote` in them for clues - eg

```
$ fgrep -i mote ~/.octoprint/logs/octoprint.log
2021-07-27 21:14:50,245 - octoprint.plugins.mote_lighting_control - INFO - Initialising Mote(USB) Lighting
2021-07-27 21:14:50,320 - octoprint.plugins.mote_lighting_control - INFO - Successfully initialised Mote(USB)
2021-07-27 21:14:50,327 - octoprint.plugins.mote_lighting_control - INFO - Mote: Setting lighting for event Startup to colour #3030ff
2021-07-27 21:14:53,444 - octoprint.plugins.mote_lighting_control - INFO - Startup of Mote Lighting
```

I am expecting you to see the first of those log lines, followed by `Error initialising Mote(USB)` and hopefully `Initialising Mote(PHAT) Lighting` - and lets see what happens next.  Also have a more detailed look in the area of the log file where those messages are... in case it all fell over (should be python tracebacks if so).

As for the menu issue - I'm obviously working with a wider screen than you, and I'll think about a better way to do this (I also have some other buttons on there).

**Comment by steveharman** [comment]
Hi Nigel,

Here's what I get when I grep the `octoprint.log` for "mote"

```
pi@octopi:~/.octoprint/logs $ cat octoprint.log | grep -i mote
|  Mote Lighting Control (0.3.3) = /home/pi/oprint/lib/python3.7/site-packages/octoprint_mote_lighting_control
2021-07-30 14:10:56,593 - octoprint.plugins.mote_lighting_control - INFO - Initialising Mote(USB) Lighting
2021-07-30 14:10:56,612 - octoprint.plugins.mote_lighting_control - ERROR - Error initialising Mote(USB) - Unable to find Mote device
2021-07-30 14:10:56,613 - octoprint.plugins.mote_lighting_control - INFO - Initialising Mote(PHAT) Lighting
2021-07-30 14:10:56,613 - octoprint.plugins.mote_lighting_control - INFO - Successfully initialised Mote(PHAT)
2021-07-30 14:10:56,631 - octoprint.plugins.mote_lighting_control - INFO - Mote: Setting lighting for event Startup to colour #3030ff
2021-07-30 14:10:59,376 - octoprint.plugins.mote_lighting_control - INFO - Startup of Mote Lighting
2021-07-30 14:10:59,778 - octoprint.plugins.tracking - INFO - Sent tracking event pong, payload: {'version': '1.6.1', 'os': 'linux', 'bits': 32, 'python': '3.7.3', 'pip': '20.3.3', 'cores': 4, 'freq': 1500.0, 'ram': 1903988736, 'pi_model': 'Raspberry Pi 4 Model B Rev 1.1', 'octopi_version': '0.18.0', 'plugins': 'mote_lighting_control:0.3.3'}
```

When I tail the log and toggle the LightingControl plugin in Octoprint on & off (enable/disable in Plugin Manager) I see new entries written to the log as expected:

```
2021-07-30 14:13:35,346 - octoprint.plugins.tracking - INFO - Sent tracking event disable_plugin, payload: {'plugin': 'mote_lighting_control', 'plugin_version': '0.3.3'}
2021-07-30 14:13:40,254 - octoprint.plugins.tracking - INFO - Sent tracking event enable_plugin, payload: {'plugin': 'mote_lighting_control', 'plugin_version': '0.3.3'}
```

If I use the plugin's manual-control "lightbulb" icon in Octoprint, no events seem to be written to the log.  Is that expected?

Regarding the lightbulb replacing the "System" menu item  in Octoprint's menu bar, I'm not sure if it's a screen width issue?  My desktop screen is @ 1920 wide, here's what I get:

<img width="1867" alt="moteMenuBar" src="https://user-images.githubusercontent.com/12557929/127658618-b1a96c42-a050-45dd-9401-1dd81a6ed1ec.png">

**Comment by nigelm** [comment]
Can we check that the really basic motephat control works as I would expect - basically exactly as pimoroni sample code suggests.

On the pi, ideally as the same user that OctoPrint is running as (this makes a test directory but at the end you can delete that and there will be no system changes), do this:-

```bash
$ mkdir test
$ cd test
$ python3 -m venv venv
$ . venv/bin/activate
$ pip install motephat
Looking in indexes: https://pypi.org/simple, https://www.piwheels.org/simple
Collecting motephat
  Using cached https://files.pythonhosted.org/packages/30/30/e37e3e12f3721c22b8a20b5d553fb6fc1872aa04e5f0c2dcb4cfe4e00674/motephat-0.0.3-py3-none-any.whl
Collecting RPi.GPIO (from motephat)
  Using cached https://www.piwheels.org/simple/rpi-gpio/RPi.GPIO-0.7.0-cp37-cp37m-linux_armv7l.whl
Installing collected packages: RPi.GPIO, motephat
Successfully installed RPi.GPIO-0.7.0 motephat-0.0.3
```
Then try this in python's interactive mode (the >>> and ... are prompts from python - don't type them, and the line after the for loop must be indented)
```bash
$ python
Python 3.7.3 (default, Jan 22 2021, 20:04:44)
[GCC 8.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import motephat
>>> mote = motephat
>>> for channel in range(1,5):
...   mote.configure_channel(channel=channel,num_pixels=16)
...
>>> mote.set_all(r=255,g=0,b=0, brightness=1.0)
>>> mote.show()
```
You should have LEDS on in red, if not then something is weird...
If that does fail to work than can you try the same thing but without involving the mote variable I set up (makes it look more like how the code in the plugin is setup):-
```bash
$ python
Python 3.7.3 (default, Jan 22 2021, 20:04:44)
[GCC 8.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import motephat
>>> for channel in range(1,5):
...   motephat.configure_channel(channel=channel,num_pixels=16)
...
>>> motephat.set_all(r=255,g=0,b=0, brightness=1.0)
>>> motephat.show()
```
Let me know what happens here...

**Comment by steveharman** [comment]
Hi Nigel.

Following your script, everything worked as you described; two strips of red LEDs from channels 1 & 2 on the mote phat (I only have two strips).  My Octo is running as user `pi` and `pip` reported that `motephat` was already present.

Steve

![phatRed](https://user-images.githubusercontent.com/12557929/127985339-e8c3aaef-bfa8-46d9-a7d6-d99f668e16a5.jpg)

**Comment by steveharman** [comment]
Hi @nigelm 

Well there we are...  it was a hardware issue.  ;-)

I re-soldered all the pins on the GPIO header that's connected to the PHAT and I can now control my two Mote-PHAT LED strips from the little bulb icon your plugin adds to OctoPrint.  Weird thing is that the test scripts that Pimoroni supplied in their /examples directory seemed to work - perhaps they use some other control method.

Anyway I've just started a print so we'll see if "change colour on event" causes the LEDs to switch to pink when the run is complete.

Cheers,

Steve

**Comment by steveharman** [comment]
Confirmed @nigelm - event based colour changing is working fine with the Mote PHAT.  Thanks for your effort with this - do you plan to push a plugin update to the OctoPrint plugin "store" ?

<img width="1573" alt="PRINTER_LEDS" src="https://user-images.githubusercontent.com/12557929/132464598-c8adff0b-3f1f-4d54-9d25-001a0e31648e.png">

**Comment by nigelm** [comment]
I pushed version 0.4.0 a week back which has the phat support and some other bug fixes.  I haven't got any other changes in the pipeline.

I'll close this issue now.
