### ISSUE TITLE
Plugin breaks login status of OctoPrint Web GUI

### ISSUE THREAD

**Issue by mustex** [nigelm/OctoPrint-MoteLightingControl#3]
After installing thius plugin, the Octopi header always shows that the user is not logged in.  This in turn causes the system menu items to be hidden. This means that the user cannot shutdown/reboot the PI or restart the octoprint service from the octoprint menu,.

![PluginLoginIncorrect](https://user-images.githubusercontent.com/2503072/128563137-f67bc822-0b21-48f9-86df-97eace578a23.png)

Disabling or removing the plugin restores the correct login status in the header as well as the system menu item.

![PluginLoginCorrect](https://user-images.githubusercontent.com/2503072/128562889-895b297a-4eec-4df2-beae-5ec4b823921d.png)

**Comment by mustex** [comment]
I'm assuming this has something to do with this KO error that shows up in the Chrome dev console:

![KOError](https://user-images.githubusercontent.com/2503072/128564731-88a19465-7b80-4109-a0da-0a75b0270986.png)

````
Could not bind view model MoteLightingControlViewModel to target #settings_plugin_mote_lighting_control : Error: You cannot apply bindings multiple times to the same element.

Could not bind view model NavigationViewModel to target #navbar : Error: You cannot apply bindings multiple times to the same element.
````

**Comment by cmlaven** [comment]
Seeing the same issue on my instance of Octopi/Octoprint with this plugin.

**Comment by 46Ranger** [comment]
Also seeing the same issue on my instance of Octopi/Octoprint with this plugin.

**Comment by nigelm** [comment]
Sorry - been out of things for a month or so, and wasn't getting any issue notifications.
